---
- name: Build and run Script CRUD Application container for Node.js app
  hosts: app_host
  gather_facts: false

  tasks:
    - name: Copy sources to build target
      ansible.builtin.copy:
        src: "../../src"
        dest: "/tmp/crud-app"

    - name: Build Docker image
      community.docker.docker_image:
        source: build
        build:
          path: "/tmp/crud-app/src"
          nocache: true
        name: script_crud_app
        push: false
        tag: latest
        force_source: true

    - name: Run Docker container
      community.docker.docker_container:
        name: script_crud_app
        image: script_crud_app:latest
        ports:
          - "8082:8080"
        env:
          PORT: "8080"
        state: started
        restart: true
        restart_policy: always
